name: starklings Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Rust v1.80.1
        run: rustup default 1.80.1
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
